name: Documentation Update
description: Request an update or improvement to documentation
title: "[DOCS] "
labels: ["documentation", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation! Clear documentation helps everyone.

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation needs updating?
      options:
        - README
        - Installation Guide
        - Configuration Guide
        - Usage Guide
        - API Documentation
        - Code Comments
        - Architecture Documentation
        - Troubleshooting Guide
        - Other
    validations:
      required: true

  - type: textarea
    id: issue
    attributes:
      label: Documentation Issue
      description: What is unclear, missing, or incorrect in the current documentation?
      placeholder: The current documentation says... but it should say...
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Location
      description: Where in the documentation is this issue? (file path, section, URL)
      placeholder: e.g., README.md - Installation section, line 45
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: How should the documentation be updated?
      placeholder: I suggest we update it to explain...
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, examples, or references
      placeholder: Any additional information...

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have checked that this documentation issue hasn't already been reported
          required: true
        - label: I am willing to submit a pull request to fix this documentation issue
          required: false
