name: Feature Request
description: Suggest a new feature or enhancement for the Advanced Audit History PCF Control
title: "[FEATURE] "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! We appreciate your input to make this control better.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: I would like the control to...
    validations:
      required: true

  - type: dropdown
    id: feature-category
    attributes:
      label: Feature Category
      description: Which area does this feature relate to?
      options:
        - Analytics & Reporting
        - Filtering & Search
        - Visualization (Timeline, Charts)
        - Export Functionality
        - Notifications & Alerts
        - Security & Compliance
        - Performance Optimization
        - Integration (Power BI, Power Automate, Teams)
        - User Interface
        - Mobile Experience
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical - Blocks my work
        - High - Important for my use case
        - Medium - Would be nice to have
        - Low - Optional enhancement
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: I have considered...

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your specific use case for this feature
      placeholder: |
        In my organization, we need to...
        This would help us by...
    validations:
      required: true

  - type: textarea
    id: mockups
    attributes:
      label: Mockups or Examples
      description: If applicable, add mockups, screenshots, or links to examples of similar functionality
      placeholder: Drag and drop images here or paste URLs

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, compliance requirements, or technical considerations
      placeholder: Any additional information...

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues and feature requests to ensure this is not a duplicate
          required: true
        - label: This feature aligns with the project's goals for enterprise audit management
          required: true
        - label: I am willing to help test this feature if implemented
          required: false
