name: Question or Support
description: Ask a question or get help using the Advanced Audit History PCF Control
title: "[QUESTION] "
labels: ["question", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for your question! We're here to help you get the most out of the Advanced Audit History Control.
        
        Before asking, please check:
        - [Documentation](../../README.md)
        - [Existing Issues](../../issues)
        - [Discussions](../../discussions)

  - type: dropdown
    id: question-type
    attributes:
      label: Question Type
      description: What type of help do you need?
      options:
        - Installation & Setup
        - Configuration
        - Usage & How-To
        - Integration (Power BI, Power Automate, Teams)
        - Performance Optimization
        - Troubleshooting
        - Best Practices
        - Licensing & Compliance
        - Other
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: How do I...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide context about your environment and what you're trying to achieve
      placeholder: |
        Environment: Dynamics 365 Online / Power Apps
        Control Version: 2.0.0
        Goal: I'm trying to...
    validations:
      required: true

  - type: textarea
    id: attempted-solutions
    attributes:
      label: What Have You Tried?
      description: What steps have you already taken to solve this?
      placeholder: |
        1. I tried...
        2. I checked...
        3. I configured...

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or Code
      description: If applicable, add screenshots or code snippets to clarify your question
      placeholder: Drag and drop images or paste code here...

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Any other information that might be helpful
      placeholder: Any additional context...

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues and discussions for similar questions
          required: true
        - label: I have reviewed the documentation
          required: true
        - label: This is not a bug report or feature request (those should use their respective templates)
          required: true
